import { Inter } from "next/font/google";
import "./styles/globals.css"
import { Header } from "@/components/custom/Header";
import { Footer } from "@/components/custom/Footer";
import { getGlobalPageData } from "@/data/loaders";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const globalData = await getGlobalPageData();

  return (
    <html lang="en">
      <body className="bg-bg text-white">
      <Header data={globalData.header}></Header>
       <div className="grid w-full">
        {children}
       </div>   
      <Footer data={globalData.footer} className=""></Footer>
        </body>
    </html>
  );
}
